run:
  go: '1.17'
  skip-dirs-use-default: false
  tests: true

issues:
  max-same-issues: 0

linters-settings:
  gosec:
    excludes:
      - G204

  cyclop:
    max-complexity: 20

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/www-golang-courses-ru/advanced-dealing-with-panic-in-go)

  lll:
    line-length: 130

  nestif:
    min-complexity: 7

  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - deadcode
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - grouper
    - errcheck
    - errchkjson
    - errname
    - exhaustive
    - exportloopref
    - funlen
    #    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - lll
    - maintidx
    - makezero
    - misspell
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - tenv
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - varcheck
    - wastedassign
    - whitespace
