version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - my_volume:/var/lib/postgresql/data

volumes:
  my_volume: